/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package admin_panel;

/**
 *
 * @author Khizar Fayyaz
 */
public class admin_panel extends javax.swing.JFrame {

    /**
     * Creates new form admin_panel
     */
    public admin_panel() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();
        lbl_welcome = new javax.swing.JLabel();
        btn_so = new javax.swing.JButton();
        btn_paragraph = new javax.swing.JButton();
        btn_word = new javax.swing.JButton();
        btn_changepw = new javax.swing.JButton();

        btn_back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_back.setText("Back");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_welcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_welcome.setText("Welcome Admin");

        btn_so.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_so.setForeground(new java.awt.Color(0, 0, 255));
        btn_so.setText("Sign Out");
        btn_so.setBorderPainted(false);
        btn_so.setContentAreaFilled(false);
        btn_so.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_so.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_soActionPerformed(evt);
            }
        });

        btn_paragraph.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_paragraph.setText("Paragraph Management");
        btn_paragraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_paragraphActionPerformed(evt);
            }
        });

        btn_word.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_word.setText("Word Management");
        btn_word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_wordActionPerformed(evt);
            }
        });

        btn_changepw.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_changepw.setText("Change Password");
        btn_changepw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changepwActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_so))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_word)
                                    .addComponent(lbl_welcome))
                                .addGap(10, 110, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_paragraph, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_changepw)
                                .addGap(114, 114, 114)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_so)
                .addGap(19, 19, 19)
                .addComponent(lbl_welcome)
                .addGap(43, 43, 43)
                .addComponent(btn_word)
                .addGap(37, 37, 37)
                .addComponent(btn_paragraph)
                .addGap(30, 30, 30)
                .addComponent(btn_changepw)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_soActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_soActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        admin_login ag=new admin_login();
        ag.setVisible(true);
        
    }//GEN-LAST:event_btn_soActionPerformed

    private void btn_wordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_wordActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        word_management wm=new word_management();
        wm.setVisible(true);
    }//GEN-LAST:event_btn_wordActionPerformed

    private void btn_paragraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paragraphActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        paragraph_management pm=new paragraph_management();
        pm.setVisible(true);
    }//GEN-LAST:event_btn_paragraphActionPerformed

    private void btn_changepwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changepwActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        change_pw cp=new change_pw();
        cp.setVisible(true);
    }//GEN-LAST:event_btn_changepwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_changepw;
    private javax.swing.JButton btn_paragraph;
    private javax.swing.JButton btn_so;
    private javax.swing.JButton btn_word;
    private javax.swing.JLabel lbl_welcome;
    // End of variables declaration//GEN-END:variables
}
